### ISSUE TITLE
Discussion Polls Disabled.

### ISSUE THREAD

**Issue by the-REAL-beautysleep** [hgtonight/Plugin-DiscussionPolls#18]
I don't seem to be able to enable this in Vanilla 3.2 

Canonical URL https://example.com/idea_factory/settings/plugins !== https://example.com/idea_factory/dashboard/settings/plugins.

#0 [internal function]: gdn_ErrorHandler(1024, 'Canonical URL h...', '/home/cpanelUserName/...', 863, Array)
#1 /home/cpanelUserName/public_html/idea_factory/library/core/class.dispatcher.php(863): trigger_error('Canonical URL h...', 1024)
#2 /home/cpanelUserName/public_html/idea_factory/library/core/class.dispatcher.php(289): Gdn_Dispatcher->dispatchController(Object(Gdn_Request), Array)
#3 /home/cpanelUserName/public_html/idea_factory/index.php(29): Gdn_Dispatcher->dispatch()
#4 {main}

**Comment by the-REAL-beautysleep** [comment]
when I open phpMyAdmin I don't see a table named GDN_DiscussionPolls. Am I supposed to add this manually?
also Fatal Error in PHP.gdn_ErrorHandler();

'Table \'cPanelUsername_PHPtable.GDN_DiscussionPolls\' doesn\'t exist'

edit
Ok so I see that class.DiscussionPollsModel.php should make the Gdn_Model 

/home/cpanelUserName/public_html/idea_factory/library/database/class.database.phpPHP::gdn_ErrorHandler();
[/home/cpanelUserName/public_html/idea_factory/library/database/class.database.php:421] PHP::trigger_error();
[/home/cpanelUserName/public_html/idea_factory/library/database/class.sqldriver.php:1707] Gdn_Database->query();
[/home/cpanelUserName/public_html/idea_factory/library/database/class.sqldriver.php:664] Gdn_SQLDriver->query();
[/home/cpanelUserName/public_html/idea_factory/plugins/discussionpolls/class.discussionpollsmodel.php:47] Gdn_SQLDriver->get();
[/home/cpanelUserName/public_html/idea_factory/plugins/discussionpolls/class.discussionpolls.plugin.php:497] DiscussionPollsModel->Exists();
[/home/cpanelUserName/public_html/idea_factory/plugins/discussionpolls/class.discussionpolls.plugin.php:263] DiscussionPollsPlugin->_PollInsertion();
[/home/cpanelUserName/public_html/idea_factory/plugins/discussionpolls/class.discussionpolls.plugin.php:263] DiscussionPollsPlugin->DiscussionController_AfterDiscussionBody_Handler();
[/home/cpanelUserName/public_html/idea_factory/library/Garden/EventManager.php:278] PHP::call_user_func_array();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.pluginmanager.php:810] Garden\EventManager->fire();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.pluginmanager.php:768] Gdn_PluginManager->callEventHandler();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.pluggable.php:137] Gdn_PluginManager->callEventHandlers();
[/home/cpanelUserName/public_html/idea_factory/applications/vanilla/views/discussion/discussion.php:93] Gdn_Pluggable->fireEvent();
[/home/cpanelUserName/public_html/idea_factory/applications/vanilla/views/discussion/index.php:31] PHP::include();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.controller.php:782] PHP::include();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.controller.php:1386] Gdn_Controller->fetchView();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.pluggable.php:217] Gdn_Controller->xRender();
[/home/cpanelUserName/public_html/idea_factory/applications/vanilla/controllers/class.discussioncontroller.php:310] Gdn_Pluggable->__call();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.dispatcher.php:872] DiscussionController->index();
[/home/cpanelUserName/public_html/idea_factory/library/core/class.dispatcher.php:289] Gdn_Dispatcher->dispatchController();
[/home/cpanelUserName/public_html/idea_factory/index.php:29] Gdn_Dispatcher->dispatch();


looking at this line specifically     [/home/cpanelUserName/public_html/idea_factory/applications/vanilla/views/discussion/discussion.php:93] Gdn_Pluggable->fireEvent();
representing this 
                <?php
                $this->fireEvent('AfterDiscussionBody');
                writeReactions($Discussion);
                if (val('Attachments', $Discussion)) {
                    writeAttachments($Discussion->Attachments);
                }
                ?>


I wonder if this is any hint vvv
/home/cpanelUserName/public_html/idea_factory/applications/vanilla/views/discussion/discussion.php line 80.
           $this->fireEvent('AfterDiscussionMeta'); // DEPRECATED which
